List <Map<String, dynamic>> userData = [

];

List <Map<String, dynamic>> borrowedBooks = [

];

List<Map<String, String>> librarianData = [
  {'name': 'alice', 'password': 'alice123', 'email': 'alice@example.com', 'phone': '1234567890'},
  {'name': 'bob', 'password': 'bob123', 'email': 'bob@example.com', 'phone': '1234567891'},
  {'name': 'carol', 'password': 'carol123', 'email': 'carol@example.com', 'phone': '1234567892'},
  {'name': 'david', 'password': 'david123', 'email': 'david@example.com', 'phone': '1234567893'},
  {'name': 'eva', 'password': 'eva123', 'email': 'eva@example.com', 'phone': '1234567894'},
  {'name': 'frank', 'password': 'frank123', 'email': 'frank@example.com', 'phone': '1234567895'},
  {'name': 'grace', 'password': 'grace123', 'email': 'grace@example.com', 'phone': '1234567896'},
  {'name': 'henry', 'password': 'henry123', 'email': 'henry@example.com', 'phone': '1234567897'},
  {'name': 'irene', 'password': 'irene123', 'email': 'irene@example.com', 'phone': '1234567898'},
  {'name': 'jack', 'password': 'jack123', 'email': 'jack@example.com', 'phone': '1234567899'},
  {'name': 'karen', 'password': 'karen123', 'email': 'karen@example.com', 'phone': '1234567800'},
  {'name': 'leo', 'password': 'leo123', 'email': 'leo@example.com', 'phone': '1234567801'},
  {'name': 'mia', 'password': 'mia123', 'email': 'mia@example.com', 'phone': '1234567802'},
  {'name': 'nathan', 'password': 'nathan123', 'email': 'nathan@example.com', 'phone': '1234567803'},
  {'name': 'olivia', 'password': 'olivia123', 'email': 'olivia@example.com', 'phone': '1234567804'},
];


List<Map<String, dynamic>> bookData = [
  {
    'name': 'understanding medicine',
    'author': 'emily johnson',
    'publisher': 'bantam books',
    'classification': 'engineering',
    'year': '1626',
    'volumes': 3,
    'pages': 555,
  },
  {
    'name': 'essentials of psychology',
    'author': 'jessica davis',
    'publisher': 'oxford press',
    'classification': 'history',
    'year': '1913',
    'volumes': 1,
    'pages': 415,
  },
  {
    'name': 'essentials of politics',
    'author': 'mary thomas',
    'publisher': 'simon & schuster',
    'classification': 'art',
    'year': '1648',
    'volumes': 3,
    'pages': 298,
  },
  {
    'name': 'foundations of philosophy',
    'author': 'emily johnson',
    'publisher': 'springer',
    'classification': 'history',
    'year': '1730',
    'volumes': 3,
    'pages': 449,
  },
  {
    'name': 'the future of science',
    'author': 'emily johnson',
    'publisher': 'scholastic',
    'classification': 'art',
    'year': '1556',
    'volumes': 3,
    'pages': 261,
  },
  {
    'name': 'essentials of psychology',
    'author': 'linda martinez',
    'publisher': 'oxford press',
    'classification': 'science',
    'year': '1939',
    'volumes': 2,
    'pages': 349,
  },
  {
    'name': 'understanding biology',
    'author': 'sarah lee',
    'publisher': 'bantam books',
    'classification': 'engineering',
    'year': '1736',
    'volumes': 3,
    'pages': 220,
  },
  {
    'name': 'understanding literature',
    'author': 'jessica davis',
    'publisher': 'springer',
    'classification': 'medicine',
    'year': '1553',
    'volumes': 1,
    'pages': 484,
  },
  {
    'name': 'understanding religion',
    'author': 'mary thomas',
    'publisher': 'cambridge press',
    'classification': 'astronomy',
    'year': '1852',
    'volumes': 1,
    'pages': 595,
  },
  {
    'name': 'essentials of science',
    'author': 'james taylor',
    'publisher': 'bantam books',
    'classification': 'politics',
    'year': '1529',
    'volumes': 3,
    'pages': 317,
  },
  {
    'name': 'introduction to politics',
    'author': 'emily johnson',
    'publisher': 'cambridge press',
    'classification': 'history',
    'year': '1676',
    'volumes': 2,
    'pages': 245,
  },
  {
    'name': 'foundations of politics',
    'author': 'mary thomas',
    'publisher': 'simon & schuster',
    'classification': 'politics',
    'year': '1714',
    'volumes': 3,
    'pages': 106,
  },
  {
    'name': 'advanced art',
    'author': 'john smith',
    'publisher': 'harpercollins',
    'classification': 'technology',
    'year': '1935',
    'volumes': 1,
    'pages': 567,
  },
  {
    'name': 'understanding science',
    'author': 'michael brown',
    'publisher': 'simon & schuster',
    'classification': 'medicine',
    'year': '1720',
    'volumes': 3,
    'pages': 443,
  },
  {
    'name': 'essentials of politics',
    'author': 'sarah lee',
    'publisher': 'random house',
    'classification': 'philosophy',
    'year': '1530',
    'volumes': 2,
    'pages': 510,
  },
  {
    'name': 'the future of psychology',
    'author': 'john smith',
    'publisher': 'bantam books',
    'classification': 'history',
    'year': '1850',
    'volumes': 3,
    'pages': 975,
  },
  {
    'name': 'introduction to mathematics',
    'author': 'linda martinez',
    'publisher': 'cambridge press',
    'classification': 'science',
    'year': '1811',
    'volumes': 1,
    'pages': 598,
  },
  {
    'name': 'introduction to engineering',
    'author': 'james taylor',
    'publisher': 'macmillan',
    'classification': 'biology',
    'year': '1709',
    'volumes': 2,
    'pages': 659,
  },
  {
    'name': 'a guide to psychology',
    'author': 'linda martinez',
    'publisher': 'springer',
    'classification': 'psychology',
    'year': '1769',
    'volumes': 2,
    'pages': 174,
  },
  {
    'name': 'the art of engineering',
    'author': 'mary thomas',
    'publisher': 'oxford press',
    'classification': 'history',
    'year': '1545',
    'volumes': 1,
    'pages': 885,
  },
  {
    'name': 'advanced psychology',
    'author': 'michael brown',
    'publisher': 'macmillan',
    'classification': 'medicine',
    'year': '1699',
    'volumes': 3,
    'pages': 176,
  },
  {
    'name': 'foundations of religion',
    'author': 'james taylor',
    'publisher': 'oxford press',
    'classification': 'engineering',
    'year': '1990',
    'volumes': 2,
    'pages': 828,
  },
  {
    'name': 'advanced biology',
    'author': 'mary thomas',
    'publisher': 'macmillan',
    'classification': 'literature',
    'year': '1891',
    'volumes': 3,
    'pages': 626,
  },
  {
    'name': 'the future of religion',
    'author': 'james taylor',
    'publisher': 'cambridge press',
    'classification': 'religion',
    'year': '1851',
    'volumes': 3,
    'pages': 581,
  },
  {
    'name': 'the future of physics',
    'author': 'james taylor',
    'publisher': 'macmillan',
    'classification': 'astronomy',
    'year': '1684',
    'volumes': 1,
    'pages': 220,
  },
  {
    'name': 'principles of biology',
    'author': 'robert anderson',
    'publisher': 'macmillan',
    'classification': 'engineering',
    'year': '1537',
    'volumes': 3,
    'pages': 299,
  },
  {
    'name': 'principles of medicine',
    'author': 'mary thomas',
    'publisher': 'macmillan',
    'classification': 'art',
    'year': '1548',
    'volumes': 1,
    'pages': 776,
  },
  {
    'name': 'the future of physics',
    'author': 'linda martinez',
    'publisher': 'bantam books',
    'classification': 'psychology',
    'year': '1660',
    'volumes': 1,
    'pages': 349,
  },
  {
    'name': 'foundations of technology',
    'author': 'linda martinez',
    'publisher': 'penguin books',
    'classification': 'history',
    'year': '1745',
    'volumes': 1,
    'pages': 428,
  },
  {
    'name': 'the art of astronomy',
    'author': 'mary thomas',
    'publisher': 'macmillan',
    'classification': 'biology',
    'year': '1587',
    'volumes': 1,
    'pages': 722,
  },
  {
    'name': 'advanced history',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1957',
    'volumes': 1,
    'pages': 491,
  },
  {
    'name': 'understanding science',
    'author': 'linda martinez',
    'publisher': 'cambridge press',
    'classification': 'philosophy',
    'year': '1505',
    'volumes': 2,
    'pages': 900,
  },
  {
    'name': 'foundations of psychology',
    'author': 'john smith',
    'publisher': 'penguin books',
    'classification': 'biology',
    'year': '1836',
    'volumes': 1,
    'pages': 600,
  },
  {
    'name': 'advanced politics',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'psychology',
    'year': '1629',
    'volumes': 2,
    'pages': 608,
  },
  {
    'name': 'understanding biology',
    'author': 'mary thomas',
    'publisher': 'simon & schuster',
    'classification': 'history',
    'year': '1614',
    'volumes': 2,
    'pages': 506,
  },
  {
    'name': 'advanced history',
    'author': 'jessica davis',
    'publisher': 'scholastic',
    'classification': 'engineering',
    'year': '1705',
    'volumes': 1,
    'pages': 718,
  },
  {
    'name': 'the art of psychology',
    'author': 'emily johnson',
    'publisher': 'cambridge press',
    'classification': 'astronomy',
    'year': '1586',
    'volumes': 2,
    'pages': 691,
  },
  {
    'name': 'advanced art',
    'author': 'mary thomas',
    'publisher': 'oxford press',
    'classification': 'medicine',
    'year': '1768',
    'volumes': 1,
    'pages': 674,
  },
  {
    'name': 'principles of science',
    'author': 'robert anderson',
    'publisher': 'random house',
    'classification': 'psychology',
    'year': '1955',
    'volumes': 2,
    'pages': 335,
  },
  {
    'name': 'principles of astronomy',
    'author': 'robert anderson',
    'publisher': 'macmillan',
    'classification': 'art',
    'year': '1800',
    'volumes': 2,
    'pages': 357,
  },
  {
    'name': 'advanced astronomy',
    'author': 'robert anderson',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1580',
    'volumes': 1,
    'pages': 575,
  },
  {
    'name': 'modern literature',
    'author': 'john smith',
    'publisher': 'simon & schuster',
    'classification': 'astronomy',
    'year': '1895',
    'volumes': 1,
    'pages': 167,
  },
  {
    'name': 'understanding technology',
    'author': 'michael brown',
    'publisher': 'cambridge press',
    'classification': 'psychology',
    'year': '1797',
    'volumes': 3,
    'pages': 498,
  },
  {
    'name': 'introduction to art',
    'author': 'mary thomas',
    'publisher': 'macmillan',
    'classification': 'mathematics',
    'year': '1732',
    'volumes': 1,
    'pages': 530,
  },
  {
    'name': 'understanding technology',
    'author': 'michael brown',
    'publisher': 'random house',
    'classification': 'art',
    'year': '1623',
    'volumes': 1,
    'pages': 738,
  },
  {
    'name': 'the future of art',
    'author': 'james taylor',
    'publisher': 'cambridge press',
    'classification': 'technology',
    'year': '1881',
    'volumes': 3,
    'pages': 792,
  },
  {
    'name': 'a guide to science',
    'author': 'michael brown',
    'publisher': 'harpercollins',
    'classification': 'mathematics',
    'year': '1722',
    'volumes': 1,
    'pages': 758,
  },
  {
    'name': 'the art of physics',
    'author': 'linda martinez',
    'publisher': 'cambridge press',
    'classification': 'religion',
    'year': '1931',
    'volumes': 1,
    'pages': 618,
  },
  {
    'name': 'principles of mathematics',
    'author': 'jessica davis',
    'publisher': 'random house',
    'classification': 'religion',
    'year': '1574',
    'volumes': 2,
    'pages': 365,
  },
  {
    'name': 'modern medicine',
    'author': 'david wilson',
    'publisher': 'springer',
    'classification': 'physics',
    'year': '1885',
    'volumes': 2,
    'pages': 419,
  },
  {
    'name': 'the future of art',
    'author': 'linda martinez',
    'publisher': 'penguin books',
    'classification': 'politics',
    'year': '1536',
    'volumes': 1,
    'pages': 580,
  },
  {
    'name': 'modern engineering',
    'author': 'michael brown',
    'publisher': 'penguin books',
    'classification': 'biology',
    'year': '1907',
    'volumes': 1,
    'pages': 760,
  },
  {
    'name': 'understanding history',
    'author': 'james taylor',
    'publisher': 'simon & schuster',
    'classification': 'physics',
    'year': '1828',
    'volumes': 2,
    'pages': 429,
  },
  {
    'name': 'the art of science',
    'author': 'jessica davis',
    'publisher': 'scholastic',
    'classification': 'history',
    'year': '1984',
    'volumes': 3,
    'pages': 892,
  },
  {
    'name': 'the future of technology',
    'author': 'jessica davis',
    'publisher': 'penguin books',
    'classification': 'biology',
    'year': '1538',
    'volumes': 1,
    'pages': 951,
  },
  {
    'name': 'introduction to physics',
    'author': 'jessica davis',
    'publisher': 'penguin books',
    'classification': 'biology',
    'year': '1571',
    'volumes': 1,
    'pages': 331,
  },
  {
    'name': 'understanding medicine',
    'author': 'jessica davis',
    'publisher': 'random house',
    'classification': 'biology',
    'year': '1622',
    'volumes': 2,
    'pages': 395,
  },
  {
    'name': 'the future of biology',
    'author': 'sarah lee',
    'publisher': 'scholastic',
    'classification': 'biology',
    'year': '1643',
    'volumes': 3,
    'pages': 741,
  },
  {
    'name': 'the future of literature',
    'author': 'michael brown',
    'publisher': 'macmillan',
    'classification': 'technology',
    'year': '1988',
    'volumes': 2,
    'pages': 174,
  },
  {
    'name': 'the future of art',
    'author': 'sarah lee',
    'publisher': 'springer',
    'classification': 'science',
    'year': '1829',
    'volumes': 3,
    'pages': 703,
  },
  {
    'name': 'a guide to politics',
    'author': 'david wilson',
    'publisher': 'random house',
    'classification': 'history',
    'year': '1845',
    'volumes': 1,
    'pages': 572,
  },
  {
    'name': 'foundations of history',
    'author': 'jessica davis',
    'publisher': 'cambridge press',
    'classification': 'religion',
    'year': '1535',
    'volumes': 2,
    'pages': 994,
  },
  {
    'name': 'a guide to philosophy',
    'author': 'sarah lee',
    'publisher': 'bantam books',
    'classification': 'philosophy',
    'year': '1511',
    'volumes': 3,
    'pages': 212,
  },
  {
    'name': 'the art of religion',
    'author': 'sarah lee',
    'publisher': 'simon & schuster',
    'classification': 'medicine',
    'year': '1759',
    'volumes': 3,
    'pages': 767,
  },
  {
    'name': 'the future of literature',
    'author': 'robert anderson',
    'publisher': 'cambridge press',
    'classification': 'politics',
    'year': '1674',
    'volumes': 3,
    'pages': 917,
  },
  {
    'name': 'a guide to literature',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'engineering',
    'year': '1819',
    'volumes': 1,
    'pages': 665,
  },
  {
    'name': 'principles of biology',
    'author': 'jessica davis',
    'publisher': 'oxford press',
    'classification': 'history',
    'year': '1541',
    'volumes': 1,
    'pages': 525,
  },
  {
    'name': 'the art of literature',
    'author': 'james taylor',
    'publisher': 'cambridge press',
    'classification': 'history',
    'year': '1700',
    'volumes': 3,
    'pages': 864,
  },
  {
    'name': 'the art of history',
    'author': 'michael brown',
    'publisher': 'bantam books',
    'classification': 'biology',
    'year': '1783',
    'volumes': 1,
    'pages': 373,
  },
  {
    'name': 'understanding biology',
    'author': 'sarah lee',
    'publisher': 'springer',
    'classification': 'religion',
    'year': '1726',
    'volumes': 1,
    'pages': 168,
  },
  {
    'name': 'principles of medicine',
    'author': 'james taylor',
    'publisher': 'oxford press',
    'classification': 'politics',
    'year': '1837',
    'volumes': 1,
    'pages': 161,
  },
  {
    'name': 'the future of technology',
    'author': 'john smith',
    'publisher': 'random house',
    'classification': 'philosophy',
    'year': '1735',
    'volumes': 2,
    'pages': 467,
  },
  {
    'name': 'the future of engineering',
    'author': 'sarah lee',
    'publisher': 'cambridge press',
    'classification': 'engineering',
    'year': '1839',
    'volumes': 1,
    'pages': 164,
  },
  {
    'name': 'the art of mathematics',
    'author': 'james taylor',
    'publisher': 'macmillan',
    'classification': 'engineering',
    'year': '1962',
    'volumes': 1,
    'pages': 601,
  },
  {
    'name': 'advanced biology',
    'author': 'sarah lee',
    'publisher': 'macmillan',
    'classification': 'medicine',
    'year': '1762',
    'volumes': 1,
    'pages': 416,
  },
  {
    'name': 'essentials of technology',
    'author': 'james taylor',
    'publisher': 'scholastic',
    'classification': 'biology',
    'year': '1979',
    'volumes': 3,
    'pages': 661,
  },
  {
    'name': 'advanced literature',
    'author': 'david wilson',
    'publisher': 'simon & schuster',
    'classification': 'politics',
    'year': '2015',
    'volumes': 2,
    'pages': 471,
  },
  {
    'name': 'the art of engineering',
    'author': 'jessica davis',
    'publisher': 'simon & schuster',
    'classification': 'mathematics',
    'year': '1797',
    'volumes': 1,
    'pages': 920,
  },
  {
    'name': 'the art of mathematics',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1922',
    'volumes': 2,
    'pages': 220,
  },
  {
    'name': 'foundations of literature',
    'author': 'james taylor',
    'publisher': 'cambridge press',
    'classification': 'medicine',
    'year': '1941',
    'volumes': 2,
    'pages': 625,
  },
  {
    'name': 'modern psychology',
    'author': 'jessica davis',
    'publisher': 'bantam books',
    'classification': 'politics',
    'year': '1673',
    'volumes': 3,
    'pages': 654,
  },
  {
    'name': 'introduction to technology',
    'author': 'james taylor',
    'publisher': 'harpercollins',
    'classification': 'biology',
    'year': '1732',
    'volumes': 1,
    'pages': 465,
  },
  {
    'name': 'advanced religion',
    'author': 'michael brown',
    'publisher': 'harpercollins',
    'classification': 'biology',
    'year': '1736',
    'volumes': 1,
    'pages': 538,
  },
  {
    'name': 'understanding engineering',
    'author': 'james taylor',
    'publisher': 'cambridge press',
    'classification': 'biology',
    'year': '1845',
    'volumes': 3,
    'pages': 684,
  },
  {
    'name': 'advanced politics',
    'author': 'linda martinez',
    'publisher': 'bantam books',
    'classification': 'literature',
    'year': '1965',
    'volumes': 2,
    'pages': 228,
  },
  {
    'name': 'principles of biology',
    'author': 'david wilson',
    'publisher': 'penguin books',
    'classification': 'philosophy',
    'year': '1521',
    'volumes': 2,
    'pages': 305,
  },
  {
    'name': 'the future of medicine',
    'author': 'jessica davis',
    'publisher': 'random house',
    'classification': 'biology',
    'year': '1833',
    'volumes': 2,
    'pages': 669,
  },
  {
    'name': 'introduction to biology',
    'author': 'david wilson',
    'publisher': 'bantam books',
    'classification': 'literature',
    'year': '1962',
    'volumes': 3,
    'pages': 673,
  },
  {
    'name': 'foundations of physics',
    'author': 'emily johnson',
    'publisher': 'oxford press',
    'classification': 'technology',
    'year': '1582',
    'volumes': 2,
    'pages': 780,
  },
  {
    'name': 'introduction to religion',
    'author': 'sarah lee',
    'publisher': 'simon & schuster',
    'classification': 'philosophy',
    'year': '2025',
    'volumes': 2,
    'pages': 799,
  },
  {
    'name': 'a guide to medicine',
    'author': 'john smith',
    'publisher': 'random house',
    'classification': 'physics',
    'year': '1593',
    'volumes': 1,
    'pages': 799,
  },
  {
    'name': 'advanced philosophy',
    'author': 'david wilson',
    'publisher': 'cambridge press',
    'classification': 'astronomy',
    'year': '1544',
    'volumes': 3,
    'pages': 336,
  },
  {
    'name': 'foundations of art',
    'author': 'linda martinez',
    'publisher': 'scholastic',
    'classification': 'politics',
    'year': '1716',
    'volumes': 2,
    'pages': 227,
  },
  {
    'name': 'the future of engineering',
    'author': 'linda martinez',
    'publisher': 'springer',
    'classification': 'religion',
    'year': '1521',
    'volumes': 2,
    'pages': 504,
  },
  {
    'name': 'modern psychology',
    'author': 'linda martinez',
    'publisher': 'penguin books',
    'classification': 'astronomy',
    'year': '1635',
    'volumes': 2,
    'pages': 128,
  },
  {
    'name': 'modern philosophy',
    'author': 'james taylor',
    'publisher': 'simon & schuster',
    'classification': 'art',
    'year': '1744',
    'volumes': 2,
    'pages': 678,
  },
  {
    'name': 'understanding art',
    'author': 'emily johnson',
    'publisher': 'scholastic',
    'classification': 'religion',
    'year': '1968',
    'volumes': 1,
    'pages': 293,
  },
  {
    'name': 'principles of technology',
    'author': 'jessica davis',
    'publisher': 'macmillan',
    'classification': 'politics',
    'year': '1685',
    'volumes': 1,
    'pages': 979,
  },
  {
    'name': 'advanced religion',
    'author': 'jessica davis',
    'publisher': 'macmillan',
    'classification': 'biology',
    'year': '1743',
    'volumes': 2,
    'pages': 590,
  },
  {
    'name': 'advanced mathematics',
    'author': 'david wilson',
    'publisher': 'macmillan',
    'classification': 'mathematics',
    'year': '1817',
    'volumes': 1,
    'pages': 231,
  },
  {
    'name': 'the art of art',
    'author': 'jessica davis',
    'publisher': 'oxford press',
    'classification': 'physics',
    'year': '1775',
    'volumes': 1,
    'pages': 466,
  },
  {
    'name': 'foundations of science',
    'author': 'david wilson',
    'publisher': 'cambridge press',
    'classification': 'mathematics',
    'year': '1749',
    'volumes': 3,
    'pages': 761,
  },
  {
    'name': 'the art of psychology',
    'author': 'sarah lee',
    'publisher': 'bantam books',
    'classification': 'medicine',
    'year': '1726',
    'volumes': 1,
    'pages': 838,
  },
  {
    'name': 'the art of biology',
    'author': 'robert anderson',
    'publisher': 'penguin books',
    'classification': 'mathematics',
    'year': '1889',
    'volumes': 3,
    'pages': 695,
  },
  {
    'name': 'essentials of biology',
    'author': 'emily johnson',
    'publisher': 'macmillan',
    'classification': 'science',
    'year': '1843',
    'volumes': 2,
    'pages': 238,
  },
  {
    'name': 'a guide to politics',
    'author': 'david wilson',
    'publisher': 'penguin books',
    'classification': 'astronomy',
    'year': '1576',
    'volumes': 2,
    'pages': 319,
  },
  {
    'name': 'advanced philosophy',
    'author': 'sarah lee',
    'publisher': 'random house',
    'classification': 'biology',
    'year': '1661',
    'volumes': 1,
    'pages': 254,
  },
  {
    'name': 'foundations of biology',
    'author': 'sarah lee',
    'publisher': 'macmillan',
    'classification': 'psychology',
    'year': '1756',
    'volumes': 1,
    'pages': 788,
  },
  {
    'name': 'modern art',
    'author': 'jessica davis',
    'publisher': 'random house',
    'classification': 'medicine',
    'year': '1681',
    'volumes': 1,
    'pages': 156,
  },
  {
    'name': 'advanced religion',
    'author': 'robert anderson',
    'publisher': 'random house',
    'classification': 'physics',
    'year': '1631',
    'volumes': 3,
    'pages': 814,
  },
  {
    'name': 'advanced mathematics',
    'author': 'emily johnson',
    'publisher': 'macmillan',
    'classification': 'physics',
    'year': '2019',
    'volumes': 2,
    'pages': 100,
  },
  {
    'name': 'principles of religion',
    'author': 'emily johnson',
    'publisher': 'oxford press',
    'classification': 'philosophy',
    'year': '1797',
    'volumes': 3,
    'pages': 980,
  },
  {
    'name': 'modern astronomy',
    'author': 'james taylor',
    'publisher': 'scholastic',
    'classification': 'politics',
    'year': '1723',
    'volumes': 3,
    'pages': 344,
  },
  {
    'name': 'a guide to literature',
    'author': 'linda martinez',
    'publisher': 'springer',
    'classification': 'engineering',
    'year': '1980',
    'volumes': 3,
    'pages': 826,
  },
  {
    'name': 'advanced psychology',
    'author': 'david wilson',
    'publisher': 'springer',
    'classification': 'history',
    'year': '1830',
    'volumes': 2,
    'pages': 429,
  },
  {
    'name': 'modern art',
    'author': 'john smith',
    'publisher': 'penguin books',
    'classification': 'astronomy',
    'year': '1848',
    'volumes': 3,
    'pages': 189,
  },
  {
    'name': 'the future of science',
    'author': 'michael brown',
    'publisher': 'random house',
    'classification': 'history',
    'year': '1500',
    'volumes': 3,
    'pages': 403,
  },
  {
    'name': 'understanding history',
    'author': 'david wilson',
    'publisher': 'cambridge press',
    'classification': 'psychology',
    'year': '1713',
    'volumes': 3,
    'pages': 803,
  },
  {
    'name': 'foundations of biology',
    'author': 'david wilson',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1793',
    'volumes': 1,
    'pages': 440,
  },
  {
    'name': 'introduction to history',
    'author': 'emily johnson',
    'publisher': 'springer',
    'classification': 'technology',
    'year': '1593',
    'volumes': 1,
    'pages': 252,
  },
  {
    'name': 'the art of psychology',
    'author': 'john smith',
    'publisher': 'harpercollins',
    'classification': 'engineering',
    'year': '1735',
    'volumes': 2,
    'pages': 155,
  },
  {
    'name': 'principles of philosophy',
    'author': 'mary thomas',
    'publisher': 'random house',
    'classification': 'science',
    'year': '1636',
    'volumes': 2,
    'pages': 676,
  },
  {
    'name': 'essentials of science',
    'author': 'james taylor',
    'publisher': 'random house',
    'classification': 'psychology',
    'year': '1902',
    'volumes': 1,
    'pages': 115,
  },
  {
    'name': 'essentials of technology',
    'author': 'james taylor',
    'publisher': 'scholastic',
    'classification': 'medicine',
    'year': '1893',
    'volumes': 2,
    'pages': 825,
  },
  {
    'name': 'the art of biology',
    'author': 'jessica davis',
    'publisher': 'bantam books',
    'classification': 'mathematics',
    'year': '1934',
    'volumes': 3,
    'pages': 145,
  },
  {
    'name': 'understanding technology',
    'author': 'michael brown',
    'publisher': 'bantam books',
    'classification': 'literature',
    'year': '1865',
    'volumes': 2,
    'pages': 466,
  },
  {
    'name': 'the art of literature',
    'author': 'david wilson',
    'publisher': 'random house',
    'classification': 'philosophy',
    'year': '1703',
    'volumes': 1,
    'pages': 242,
  },
  {
    'name': 'foundations of philosophy',
    'author': 'sarah lee',
    'publisher': 'penguin books',
    'classification': 'biology',
    'year': '1710',
    'volumes': 3,
    'pages': 755,
  },
  {
    'name': 'essentials of religion',
    'author': 'mary thomas',
    'publisher': 'cambridge press',
    'classification': 'mathematics',
    'year': '1784',
    'volumes': 1,
    'pages': 245,
  },
  {
    'name': 'understanding technology',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'philosophy',
    'year': '1819',
    'volumes': 1,
    'pages': 573,
  },
  {
    'name': 'understanding art',
    'author': 'sarah lee',
    'publisher': 'oxford press',
    'classification': 'art',
    'year': '1744',
    'volumes': 3,
    'pages': 838,
  },
  {
    'name': 'the future of philosophy',
    'author': 'mary thomas',
    'publisher': 'scholastic',
    'classification': 'mathematics',
    'year': '1889',
    'volumes': 2,
    'pages': 604,
  },
  {
    'name': 'essentials of literature',
    'author': 'linda martinez',
    'publisher': 'harpercollins',
    'classification': 'engineering',
    'year': '1724',
    'volumes': 1,
    'pages': 768,
  },
  {
    'name': 'introduction to biology',
    'author': 'john smith',
    'publisher': 'scholastic',
    'classification': 'art',
    'year': '1527',
    'volumes': 3,
    'pages': 569,
  },
  {
    'name': 'understanding art',
    'author': 'emily johnson',
    'publisher': 'oxford press',
    'classification': 'biology',
    'year': '1775',
    'volumes': 3,
    'pages': 814,
  },
  {
    'name': 'principles of history',
    'author': 'james taylor',
    'publisher': 'macmillan',
    'classification': 'mathematics',
    'year': '1702',
    'volumes': 3,
    'pages': 542,
  },
  {
    'name': 'principles of history',
    'author': 'james taylor',
    'publisher': 'oxford press',
    'classification': 'mathematics',
    'year': '1863',
    'volumes': 3,
    'pages': 782,
  },
  {
    'name': 'a guide to science',
    'author': 'james taylor',
    'publisher': 'springer',
    'classification': 'psychology',
    'year': '1587',
    'volumes': 1,
    'pages': 260,
  },
  {
    'name': 'understanding medicine',
    'author': 'michael brown',
    'publisher': 'simon & schuster',
    'classification': 'biology',
    'year': '1742',
    'volumes': 3,
    'pages': 553,
  },
  {
    'name': 'understanding history',
    'author': 'jessica davis',
    'publisher': 'simon & schuster',
    'classification': 'philosophy',
    'year': '1730',
    'volumes': 1,
    'pages': 352,
  },
  {
    'name': 'introduction to astronomy',
    'author': 'david wilson',
    'publisher': 'oxford press',
    'classification': 'mathematics',
    'year': '1705',
    'volumes': 3,
    'pages': 817,
  },
  {
    'name': 'essentials of technology',
    'author': 'emily johnson',
    'publisher': 'simon & schuster',
    'classification': 'politics',
    'year': '1745',
    'volumes': 3,
    'pages': 389,
  },
  {
    'name': 'foundations of medicine',
    'author': 'mary thomas',
    'publisher': 'random house',
    'classification': 'engineering',
    'year': '1636',
    'volumes': 3,
    'pages': 467,
  },
  {
    'name': 'modern science',
    'author': 'sarah lee',
    'publisher': 'scholastic',
    'classification': 'technology',
    'year': '1650',
    'volumes': 3,
    'pages': 712,
  },
  {
    'name': 'advanced art',
    'author': 'robert anderson',
    'publisher': 'oxford press',
    'classification': 'philosophy',
    'year': '1500',
    'volumes': 3,
    'pages': 597,
  },
  {
    'name': 'understanding engineering',
    'author': 'mary thomas',
    'publisher': 'random house',
    'classification': 'physics',
    'year': '1743',
    'volumes': 1,
    'pages': 739,
  },
  {
    'name': 'modern psychology',
    'author': 'david wilson',
    'publisher': 'simon & schuster',
    'classification': 'history',
    'year': '1601',
    'volumes': 1,
    'pages': 551,
  },
  {
    'name': 'modern physics',
    'author': 'sarah lee',
    'publisher': 'simon & schuster',
    'classification': 'physics',
    'year': '1608',
    'volumes': 2,
    'pages': 918,
  },
  {
    'name': 'the future of astronomy',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'science',
    'year': '1872',
    'volumes': 3,
    'pages': 141,
  },
  {
    'name': 'the future of technology',
    'author': 'michael brown',
    'publisher': 'penguin books',
    'classification': 'astronomy',
    'year': '1514',
    'volumes': 1,
    'pages': 942,
  },
  {
    'name': 'essentials of psychology',
    'author': 'jessica davis',
    'publisher': 'springer',
    'classification': 'literature',
    'year': '1732',
    'volumes': 3,
    'pages': 349,
  },
  {
    'name': 'introduction to engineering',
    'author': 'michael brown',
    'publisher': 'random house',
    'classification': 'technology',
    'year': '1706',
    'volumes': 1,
    'pages': 601,
  },
  {
    'name': 'the future of religion',
    'author': 'robert anderson',
    'publisher': 'scholastic',
    'classification': 'history',
    'year': '1842',
    'volumes': 3,
    'pages': 151,
  },
  {
    'name': 'advanced science',
    'author': 'david wilson',
    'publisher': 'simon & schuster',
    'classification': 'medicine',
    'year': '1822',
    'volumes': 2,
    'pages': 865,
  },
  {
    'name': 'advanced medicine',
    'author': 'michael brown',
    'publisher': 'cambridge press',
    'classification': 'psychology',
    'year': '1871',
    'volumes': 3,
    'pages': 706,
  },
  {
    'name': 'understanding science',
    'author': 'linda martinez',
    'publisher': 'random house',
    'classification': 'mathematics',
    'year': '2004',
    'volumes': 3,
    'pages': 614,
  },
  {
    'name': 'introduction to religion',
    'author': 'emily johnson',
    'publisher': 'cambridge press',
    'classification': 'literature',
    'year': '1983',
    'volumes': 3,
    'pages': 729,
  },
  {
    'name': 'modern medicine',
    'author': 'robert anderson',
    'publisher': 'macmillan',
    'classification': 'physics',
    'year': '1837',
    'volumes': 2,
    'pages': 343,
  },
  {
    'name': 'modern philosophy',
    'author': 'michael brown',
    'publisher': 'macmillan',
    'classification': 'psychology',
    'year': '1962',
    'volumes': 1,
    'pages': 333,
  },
  {
    'name': 'introduction to mathematics',
    'author': 'james taylor',
    'publisher': 'oxford press',
    'classification': 'psychology',
    'year': '1819',
    'volumes': 3,
    'pages': 982,
  },
  {
    'name': 'the future of technology',
    'author': 'mary thomas',
    'publisher': 'random house',
    'classification': 'technology',
    'year': '1734',
    'volumes': 3,
    'pages': 918,
  },
  {
    'name': 'essentials of science',
    'author': 'mary thomas',
    'publisher': 'bantam books',
    'classification': 'religion',
    'year': '1715',
    'volumes': 2,
    'pages': 387,
  },
  {
    'name': 'foundations of biology',
    'author': 'john smith',
    'publisher': 'harpercollins',
    'classification': 'engineering',
    'year': '1979',
    'volumes': 2,
    'pages': 615,
  },
  {
    'name': 'a guide to medicine',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'mathematics',
    'year': '2018',
    'volumes': 2,
    'pages': 156,
  },
  {
    'name': 'introduction to physics',
    'author': 'james taylor',
    'publisher': 'bantam books',
    'classification': 'art',
    'year': '1910',
    'volumes': 1,
    'pages': 122,
  },
  {
    'name': 'understanding engineering',
    'author': 'emily johnson',
    'publisher': 'springer',
    'classification': 'biology',
    'year': '1525',
    'volumes': 2,
    'pages': 630,
  },
  {
    'name': 'essentials of history',
    'author': 'jessica davis',
    'publisher': 'scholastic',
    'classification': 'biology',
    'year': '1829',
    'volumes': 3,
    'pages': 607,
  },
  {
    'name': 'principles of biology',
    'author': 'jessica davis',
    'publisher': 'harpercollins',
    'classification': 'medicine',
    'year': '1585',
    'volumes': 1,
    'pages': 439,
  },
  {
    'name': 'foundations of technology',
    'author': 'robert anderson',
    'publisher': 'random house',
    'classification': 'art',
    'year': '1835',
    'volumes': 3,
    'pages': 787,
  },
  {
    'name': 'introduction to mathematics',
    'author': 'james taylor',
    'publisher': 'macmillan',
    'classification': 'physics',
    'year': '1984',
    'volumes': 1,
    'pages': 988,
  },
  {
    'name': 'a guide to psychology',
    'author': 'linda martinez',
    'publisher': 'macmillan',
    'classification': 'physics',
    'year': '1986',
    'volumes': 2,
    'pages': 152,
  },
  {
    'name': 'modern science',
    'author': 'emily johnson',
    'publisher': 'harpercollins',
    'classification': 'medicine',
    'year': '1869',
    'volumes': 2,
    'pages': 285,
  },
  {
    'name': 'the art of politics',
    'author': 'robert anderson',
    'publisher': 'penguin books',
    'classification': 'astronomy',
    'year': '1803',
    'volumes': 3,
    'pages': 886,
  },
  {
    'name': 'essentials of physics',
    'author': 'robert anderson',
    'publisher': 'oxford press',
    'classification': 'politics',
    'year': '1873',
    'volumes': 3,
    'pages': 149,
  },
  {
    'name': 'introduction to history',
    'author': 'michael brown',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1915',
    'volumes': 3,
    'pages': 251,
  },
  {
    'name': 'foundations of technology',
    'author': 'john smith',
    'publisher': 'cambridge press',
    'classification': 'history',
    'year': '1542',
    'volumes': 2,
    'pages': 929,
  },
  {
    'name': 'advanced biology',
    'author': 'jessica davis',
    'publisher': 'random house',
    'classification': 'politics',
    'year': '1941',
    'volumes': 2,
    'pages': 517,
  },
  {
    'name': 'modern politics',
    'author': 'michael brown',
    'publisher': 'macmillan',
    'classification': 'mathematics',
    'year': '1964',
    'volumes': 3,
    'pages': 324,
  },
  {
    'name': 'essentials of politics',
    'author': 'mary thomas',
    'publisher': 'macmillan',
    'classification': 'medicine',
    'year': '1697',
    'volumes': 1,
    'pages': 471,
  },
  {
    'name': 'understanding literature',
    'author': 'mary thomas',
    'publisher': 'cambridge press',
    'classification': 'technology',
    'year': '1722',
    'volumes': 3,
    'pages': 881,
  },
  {
    'name': 'foundations of politics',
    'author': 'sarah lee',
    'publisher': 'bantam books',
    'classification': 'physics',
    'year': '1782',
    'volumes': 3,
    'pages': 462,
  },
  {
    'name': 'essentials of mathematics',
    'author': 'linda martinez',
    'publisher': 'harpercollins',
    'classification': 'politics',
    'year': '1607',
    'volumes': 1,
    'pages': 342,
  },
  {
    'name': 'essentials of mathematics',
    'author': 'james taylor',
    'publisher': 'harpercollins',
    'classification': 'physics',
    'year': '1934',
    'volumes': 1,
    'pages': 581,
  },
  {
    'name': 'foundations of religion',
    'author': 'emily johnson',
    'publisher': 'scholastic',
    'classification': 'biology',
    'year': '1788',
    'volumes': 2,
    'pages': 555,
  },
  {
    'name': 'the future of literature',
    'author': 'john smith',
    'publisher': 'scholastic',
    'classification': 'science',
    'year': '1751',
    'volumes': 1,
    'pages': 917,
  },
  {
    'name': 'the future of science',
    'author': 'linda martinez',
    'publisher': 'random house',
    'classification': 'literature',
    'year': '1651',
    'volumes': 2,
    'pages': 404,
  },
  {
    'name': 'foundations of physics',
    'author': 'james taylor',
    'publisher': 'macmillan',
    'classification': 'engineering',
    'year': '1752',
    'volumes': 1,
    'pages': 997,
  },
  {
    'name': 'the future of psychology',
    'author': 'robert anderson',
    'publisher': 'macmillan',
    'classification': 'technology',
    'year': '1743',
    'volumes': 2,
    'pages': 874,
  },
  {
    'name': 'advanced mathematics',
    'author': 'emily johnson',
    'publisher': 'bantam books',
    'classification': 'politics',
    'year': '1662',
    'volumes': 3,
    'pages': 358,
  },
  {
    'name': 'understanding politics',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'mathematics',
    'year': '1688',
    'volumes': 3,
    'pages': 635,
  },
  {
    'name': 'essentials of technology',
    'author': 'david wilson',
    'publisher': 'random house',
    'classification': 'engineering',
    'year': '1732',
    'volumes': 3,
    'pages': 842,
  },
  {
    'name': 'the future of politics',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'technology',
    'year': '1656',
    'volumes': 3,
    'pages': 772,
  },
  {
    'name': 'essentials of psychology',
    'author': 'emily johnson',
    'publisher': 'springer',
    'classification': 'psychology',
    'year': '1906',
    'volumes': 2,
    'pages': 800,
  },
  {
    'name': 'advanced literature',
    'author': 'james taylor',
    'publisher': 'simon & schuster',
    'classification': 'engineering',
    'year': '1523',
    'volumes': 2,
    'pages': 799,
  },
  {
    'name': 'the art of philosophy',
    'author': 'sarah lee',
    'publisher': 'scholastic',
    'classification': 'psychology',
    'year': '1819',
    'volumes': 3,
    'pages': 549,
  },
  {
    'name': 'foundations of religion',
    'author': 'jessica davis',
    'publisher': 'oxford press',
    'classification': 'science',
    'year': '2019',
    'volumes': 1,
    'pages': 925,
  },
  {
    'name': 'modern biology',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'mathematics',
    'year': '1586',
    'volumes': 2,
    'pages': 520,
  },
  {
    'name': 'understanding history',
    'author': 'michael brown',
    'publisher': 'springer',
    'classification': 'psychology',
    'year': '1868',
    'volumes': 1,
    'pages': 418,
  },
  {
    'name': 'essentials of history',
    'author': 'mary thomas',
    'publisher': 'oxford press',
    'classification': 'psychology',
    'year': '1640',
    'volumes': 2,
    'pages': 166,
  },
  {
    'name': 'essentials of philosophy',
    'author': 'james taylor',
    'publisher': 'macmillan',
    'classification': 'philosophy',
    'year': '2022',
    'volumes': 2,
    'pages': 717,
  },
  {
    'name': 'the art of science',
    'author': 'david wilson',
    'publisher': 'bantam books',
    'classification': 'philosophy',
    'year': '1881',
    'volumes': 1,
    'pages': 210,
  },
  {
    'name': 'a guide to medicine',
    'author': 'jessica davis',
    'publisher': 'oxford press',
    'classification': 'technology',
    'year': '1702',
    'volumes': 3,
    'pages': 786,
  },
  {
    'name': 'a guide to engineering',
    'author': 'jessica davis',
    'publisher': 'springer',
    'classification': 'psychology',
    'year': '1611',
    'volumes': 2,
    'pages': 125,
  },
  {
    'name': 'the art of astronomy',
    'author': 'robert anderson',
    'publisher': 'random house',
    'classification': 'philosophy',
    'year': '1514',
    'volumes': 3,
    'pages': 415,
  },
  {
    'name': 'understanding engineering',
    'author': 'david wilson',
    'publisher': 'springer',
    'classification': 'literature',
    'year': '1828',
    'volumes': 3,
    'pages': 849,
  },
  {
    'name': 'the future of mathematics',
    'author': 'robert anderson',
    'publisher': 'macmillan',
    'classification': 'literature',
    'year': '1915',
    'volumes': 2,
    'pages': 246,
  },
  {
    'name': 'introduction to science',
    'author': 'jessica davis',
    'publisher': 'random house',
    'classification': 'religion',
    'year': '1818',
    'volumes': 2,
    'pages': 165,
  },
  {
    'name': 'essentials of religion',
    'author': 'john smith',
    'publisher': 'springer',
    'classification': 'psychology',
    'year': '1717',
    'volumes': 1,
    'pages': 683,
  },
  {
    'name': 'the art of engineering',
    'author': 'emily johnson',
    'publisher': 'penguin books',
    'classification': 'mathematics',
    'year': '1983',
    'volumes': 3,
    'pages': 581,
  },
  {
    'name': 'essentials of mathematics',
    'author': 'jessica davis',
    'publisher': 'scholastic',
    'classification': 'politics',
    'year': '1759',
    'volumes': 3,
    'pages': 351,
  },
  {
    'name': 'foundations of philosophy',
    'author': 'david wilson',
    'publisher': 'bantam books',
    'classification': 'medicine',
    'year': '1787',
    'volumes': 3,
    'pages': 620,
  },
  {
    'name': 'the future of art',
    'author': 'emily johnson',
    'publisher': 'random house',
    'classification': 'mathematics',
    'year': '1627',
    'volumes': 3,
    'pages': 503,
  },
  {
    'name': 'modern philosophy',
    'author': 'jessica davis',
    'publisher': 'bantam books',
    'classification': 'biology',
    'year': '1572',
    'volumes': 3,
    'pages': 695,
  },
  {
    'name': 'the art of science',
    'author': 'linda martinez',
    'publisher': 'springer',
    'classification': 'technology',
    'year': '2016',
    'volumes': 1,
    'pages': 687,
  },
  {
    'name': 'understanding engineering',
    'author': 'robert anderson',
    'publisher': 'springer',
    'classification': 'engineering',
    'year': '2018',
    'volumes': 2,
    'pages': 159,
  },
  {
    'name': 'the art of politics',
    'author': 'jessica davis',
    'publisher': 'cambridge press',
    'classification': 'politics',
    'year': '1926',
    'volumes': 1,
    'pages': 330,
  },
  {
    'name': 'essentials of physics',
    'author': 'david wilson',
    'publisher': 'random house',
    'classification': 'literature',
    'year': '1524',
    'volumes': 2,
    'pages': 954,
  },
  {
    'name': 'modern biology',
    'author': 'emily johnson',
    'publisher': 'bantam books',
    'classification': 'medicine',
    'year': '1629',
    'volumes': 3,
    'pages': 507,
  },
  {
    'name': 'a guide to biology',
    'author': 'linda martinez',
    'publisher': 'penguin books',
    'classification': 'technology',
    'year': '1881',
    'volumes': 3,
    'pages': 145,
  },
  {
    'name': 'understanding politics',
    'author': 'john smith',
    'publisher': 'random house',
    'classification': 'history',
    'year': '1595',
    'volumes': 3,
    'pages': 513,
  },
  {
    'name': 'principles of art',
    'author': 'emily johnson',
    'publisher': 'springer',
    'classification': 'technology',
    'year': '1655',
    'volumes': 2,
    'pages': 383,
  },
  {
    'name': 'essentials of philosophy',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'politics',
    'year': '1771',
    'volumes': 1,
    'pages': 714,
  },
  {
    'name': 'foundations of psychology',
    'author': 'james taylor',
    'publisher': 'oxford press',
    'classification': 'physics',
    'year': '1638',
    'volumes': 2,
    'pages': 839,
  },
  {
    'name': 'essentials of engineering',
    'author': 'mary thomas',
    'publisher': 'springer',
    'classification': 'history',
    'year': '1913',
    'volumes': 2,
    'pages': 851,
  },
  {
    'name': 'modern physics',
    'author': 'emily johnson',
    'publisher': 'scholastic',
    'classification': 'philosophy',
    'year': '1994',
    'volumes': 1,
    'pages': 749,
  },
  {
    'name': 'a guide to philosophy',
    'author': 'sarah lee',
    'publisher': 'random house',
    'classification': 'mathematics',
    'year': '1518',
    'volumes': 3,
    'pages': 536,
  },
  {
    'name': 'principles of art',
    'author': 'emily johnson',
    'publisher': 'macmillan',
    'classification': 'astronomy',
    'year': '1609',
    'volumes': 2,
    'pages': 288,
  },
  {
    'name': 'advanced philosophy',
    'author': 'james taylor',
    'publisher': 'oxford press',
    'classification': 'politics',
    'year': '1812',
    'volumes': 2,
    'pages': 680,
  },
  {
    'name': 'the future of science',
    'author': 'mary thomas',
    'publisher': 'bantam books',
    'classification': 'religion',
    'year': '1764',
    'volumes': 1,
    'pages': 301,
  },
  {
    'name': 'essentials of medicine',
    'author': 'james taylor',
    'publisher': 'cambridge press',
    'classification': 'literature',
    'year': '1865',
    'volumes': 2,
    'pages': 590,
  },
  {
    'name': 'the future of astronomy',
    'author': 'david wilson',
    'publisher': 'cambridge press',
    'classification': 'engineering',
    'year': '1908',
    'volumes': 1,
    'pages': 335,
  },
  {
    'name': 'a guide to science',
    'author': 'david wilson',
    'publisher': 'bantam books',
    'classification': 'history',
    'year': '1908',
    'volumes': 1,
    'pages': 604,
  },
  {
    'name': 'principles of art',
    'author': 'emily johnson',
    'publisher': 'random house',
    'classification': 'physics',
    'year': '1573',
    'volumes': 2,
    'pages': 748,
  },
  {
    'name': 'the art of technology',
    'author': 'jessica davis',
    'publisher': 'scholastic',
    'classification': 'science',
    'year': '1998',
    'volumes': 3,
    'pages': 744,
  },
  {
    'name': 'essentials of technology',
    'author': 'jessica davis',
    'publisher': 'scholastic',
    'classification': 'history',
    'year': '1545',
    'volumes': 3,
    'pages': 104,
  },
  {
    'name': 'foundations of psychology',
    'author': 'robert anderson',
    'publisher': 'bantam books',
    'classification': 'politics',
    'year': '1992',
    'volumes': 2,
    'pages': 113,
  },
  {
    'name': 'the art of astronomy',
    'author': 'jessica davis',
    'publisher': 'simon & schuster',
    'classification': 'mathematics',
    'year': '1821',
    'volumes': 3,
    'pages': 190,
  },
  {
    'name': 'the art of philosophy',
    'author': 'emily johnson',
    'publisher': 'springer',
    'classification': 'medicine',
    'year': '1904',
    'volumes': 1,
    'pages': 917,
  },
  {
    'name': 'a guide to politics',
    'author': 'linda martinez',
    'publisher': 'bantam books',
    'classification': 'history',
    'year': '1836',
    'volumes': 2,
    'pages': 605,
  },
  {
    'name': 'understanding astronomy',
    'author': 'linda martinez',
    'publisher': 'bantam books',
    'classification': 'astronomy',
    'year': '1925',
    'volumes': 3,
    'pages': 121,
  },
  {
    'name': 'a guide to physics',
    'author': 'robert anderson',
    'publisher': 'harpercollins',
    'classification': 'science',
    'year': '1713',
    'volumes': 2,
    'pages': 160,
  },
  {
    'name': 'the art of religion',
    'author': 'sarah lee',
    'publisher': 'penguin books',
    'classification': 'astronomy',
    'year': '1845',
    'volumes': 1,
    'pages': 589,
  },
  {
    'name': 'the art of physics',
    'author': 'jessica davis',
    'publisher': 'springer',
    'classification': 'biology',
    'year': '1918',
    'volumes': 1,
    'pages': 483,
  },
  {
    'name': 'modern engineering',
    'author': 'robert anderson',
    'publisher': 'cambridge press',
    'classification': 'politics',
    'year': '1932',
    'volumes': 2,
    'pages': 208,
  },
  {
    'name': 'foundations of art',
    'author': 'emily johnson',
    'publisher': 'bantam books',
    'classification': 'mathematics',
    'year': '1643',
    'volumes': 1,
    'pages': 309,
  },
  {
    'name': 'essentials of psychology',
    'author': 'sarah lee',
    'publisher': 'scholastic',
    'classification': 'mathematics',
    'year': '1850',
    'volumes': 3,
    'pages': 213,
  },
  {
    'name': 'understanding politics',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'mathematics',
    'year': '1644',
    'volumes': 2,
    'pages': 252,
  },
  {
    'name': 'essentials of psychology',
    'author': 'john smith',
    'publisher': 'harpercollins',
    'classification': 'literature',
    'year': '1734',
    'volumes': 3,
    'pages': 567,
  },
  {
    'name': 'the art of biology',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'physics',
    'year': '1668',
    'volumes': 2,
    'pages': 490,
  },
  {
    'name': 'advanced religion',
    'author': 'david wilson',
    'publisher': 'macmillan',
    'classification': 'astronomy',
    'year': '1939',
    'volumes': 1,
    'pages': 608,
  },
  {
    'name': 'modern biology',
    'author': 'james taylor',
    'publisher': 'bantam books',
    'classification': 'philosophy',
    'year': '1670',
    'volumes': 3,
    'pages': 909,
  },
  {
    'name': 'principles of biology',
    'author': 'john smith',
    'publisher': 'harpercollins',
    'classification': 'medicine',
    'year': '2012',
    'volumes': 1,
    'pages': 844,
  },
  {
    'name': 'essentials of astronomy',
    'author': 'jessica davis',
    'publisher': 'scholastic',
    'classification': 'technology',
    'year': '1635',
    'volumes': 2,
    'pages': 111,
  },
  {
    'name': 'modern psychology',
    'author': 'emily johnson',
    'publisher': 'random house',
    'classification': 'biology',
    'year': '1966',
    'volumes': 2,
    'pages': 622,
  },
  {
    'name': 'principles of literature',
    'author': 'michael brown',
    'publisher': 'penguin books',
    'classification': 'literature',
    'year': '1741',
    'volumes': 2,
    'pages': 971,
  },
  {
    'name': 'principles of history',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'technology',
    'year': '1938',
    'volumes': 2,
    'pages': 834,
  },
  {
    'name': 'foundations of science',
    'author': 'jessica davis',
    'publisher': 'bantam books',
    'classification': 'mathematics',
    'year': '1632',
    'volumes': 1,
    'pages': 869,
  },
  {
    'name': 'introduction to biology',
    'author': 'mary thomas',
    'publisher': 'penguin books',
    'classification': 'philosophy',
    'year': '1843',
    'volumes': 3,
    'pages': 109,
  },
  {
    'name': 'understanding engineering',
    'author': 'linda martinez',
    'publisher': 'harpercollins',
    'classification': 'philosophy',
    'year': '1931',
    'volumes': 2,
    'pages': 101,
  },
  {
    'name': 'modern engineering',
    'author': 'emily johnson',
    'publisher': 'penguin books',
    'classification': 'mathematics',
    'year': '1622',
    'volumes': 2,
    'pages': 273,
  },
  {
    'name': 'foundations of philosophy',
    'author': 'michael brown',
    'publisher': 'oxford press',
    'classification': 'biology',
    'year': '1735',
    'volumes': 1,
    'pages': 817,
  },
  {
    'name': 'understanding philosophy',
    'author': 'john smith',
    'publisher': 'random house',
    'classification': 'engineering',
    'year': '1649',
    'volumes': 1,
    'pages': 168,
  },
  {
    'name': 'a guide to psychology',
    'author': 'mary thomas',
    'publisher': 'oxford press',
    'classification': 'engineering',
    'year': '1648',
    'volumes': 2,
    'pages': 596,
  },
  {
    'name': 'principles of psychology',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'technology',
    'year': '1684',
    'volumes': 1,
    'pages': 404,
  },
  {
    'name': 'principles of astronomy',
    'author': 'david wilson',
    'publisher': 'springer',
    'classification': 'politics',
    'year': '1614',
    'volumes': 3,
    'pages': 678,
  },
  {
    'name': 'modern literature',
    'author': 'jessica davis',
    'publisher': 'springer',
    'classification': 'philosophy',
    'year': '1862',
    'volumes': 2,
    'pages': 275,
  },
  {
    'name': 'the future of medicine',
    'author': 'john smith',
    'publisher': 'scholastic',
    'classification': 'history',
    'year': '1950',
    'volumes': 2,
    'pages': 408,
  },
  {
    'name': 'introduction to physics',
    'author': 'sarah lee',
    'publisher': 'macmillan',
    'classification': 'psychology',
    'year': '1560',
    'volumes': 3,
    'pages': 148,
  },
  {
    'name': 'the art of politics',
    'author': 'robert anderson',
    'publisher': 'scholastic',
    'classification': 'history',
    'year': '1567',
    'volumes': 1,
    'pages': 541,
  },
  {
    'name': 'the future of technology',
    'author': 'michael brown',
    'publisher': 'springer',
    'classification': 'mathematics',
    'year': '1790',
    'volumes': 3,
    'pages': 145,
  },
  {
    'name': 'principles of history',
    'author': 'john smith',
    'publisher': 'scholastic',
    'classification': 'technology',
    'year': '1709',
    'volumes': 2,
    'pages': 455,
  },
  {
    'name': 'the future of psychology',
    'author': 'jessica davis',
    'publisher': 'cambridge press',
    'classification': 'literature',
    'year': '1529',
    'volumes': 1,
    'pages': 842,
  },
  {
    'name': 'modern engineering',
    'author': 'mary thomas',
    'publisher': 'springer',
    'classification': 'religion',
    'year': '1873',
    'volumes': 2,
    'pages': 498,
  },
  {
    'name': 'a guide to science',
    'author': 'john smith',
    'publisher': 'penguin books',
    'classification': 'psychology',
    'year': '1716',
    'volumes': 1,
    'pages': 607,
  },
  {
    'name': 'essentials of history',
    'author': 'robert anderson',
    'publisher': 'harpercollins',
    'classification': 'mathematics',
    'year': '1983',
    'volumes': 3,
    'pages': 960,
  },
  {
    'name': 'modern philosophy',
    'author': 'emily johnson',
    'publisher': 'harpercollins',
    'classification': 'science',
    'year': '1740',
    'volumes': 3,
    'pages': 880,
  },
  {
    'name': 'modern mathematics',
    'author': 'robert anderson',
    'publisher': 'random house',
    'classification': 'art',
    'year': '1605',
    'volumes': 1,
    'pages': 890,
  },
  {
    'name': 'modern physics',
    'author': 'linda martinez',
    'publisher': 'random house',
    'classification': 'philosophy',
    'year': '1819',
    'volumes': 1,
    'pages': 432,
  },
  {
    'name': 'a guide to mathematics',
    'author': 'david wilson',
    'publisher': 'scholastic',
    'classification': 'medicine',
    'year': '1844',
    'volumes': 2,
    'pages': 251,
  },
  {
    'name': 'advanced mathematics',
    'author': 'emily johnson',
    'publisher': 'macmillan',
    'classification': 'politics',
    'year': '1724',
    'volumes': 3,
    'pages': 608,
  },
  {
    'name': 'foundations of physics',
    'author': 'john smith',
    'publisher': 'macmillan',
    'classification': 'mathematics',
    'year': '1548',
    'volumes': 1,
    'pages': 492,
  },
  {
    'name': 'the future of astronomy',
    'author': 'mary thomas',
    'publisher': 'simon & schuster',
    'classification': 'engineering',
    'year': '1562',
    'volumes': 3,
    'pages': 643,
  },
  {
    'name': 'understanding politics',
    'author': 'john smith',
    'publisher': 'scholastic',
    'classification': 'medicine',
    'year': '1969',
    'volumes': 3,
    'pages': 674,
  },
  {
    'name': 'foundations of biology',
    'author': 'john smith',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1862',
    'volumes': 2,
    'pages': 294,
  },
  {
    'name': 'the art of psychology',
    'author': 'sarah lee',
    'publisher': 'penguin books',
    'classification': 'religion',
    'year': '1834',
    'volumes': 2,
    'pages': 291,
  },
  {
    'name': 'modern medicine',
    'author': 'michael brown',
    'publisher': 'random house',
    'classification': 'philosophy',
    'year': '1822',
    'volumes': 3,
    'pages': 415,
  },
  {
    'name': 'the future of technology',
    'author': 'james taylor',
    'publisher': 'random house',
    'classification': 'astronomy',
    'year': '1946',
    'volumes': 1,
    'pages': 134,
  },
  {
    'name': 'the art of biology',
    'author': 'mary thomas',
    'publisher': 'simon & schuster',
    'classification': 'religion',
    'year': '1564',
    'volumes': 3,
    'pages': 682,
  },
  {
    'name': 'the future of science',
    'author': 'james taylor',
    'publisher': 'oxford press',
    'classification': 'religion',
    'year': '1896',
    'volumes': 2,
    'pages': 437,
  },
  {
    'name': 'understanding engineering',
    'author': 'robert anderson',
    'publisher': 'simon & schuster',
    'classification': 'art',
    'year': '2020',
    'volumes': 2,
    'pages': 233,
  },
  {
    'name': 'understanding philosophy',
    'author': 'james taylor',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1781',
    'volumes': 2,
    'pages': 990,
  },
  {
    'name': 'advanced art',
    'author': 'robert anderson',
    'publisher': 'springer',
    'classification': 'religion',
    'year': '1706',
    'volumes': 3,
    'pages': 311,
  },
  {
    'name': 'foundations of astronomy',
    'author': 'linda martinez',
    'publisher': 'harpercollins',
    'classification': 'astronomy',
    'year': '1521',
    'volumes': 3,
    'pages': 891,
  },
  {
    'name': 'understanding biology',
    'author': 'robert anderson',
    'publisher': 'harpercollins',
    'classification': 'astronomy',
    'year': '1518',
    'volumes': 1,
    'pages': 446,
  },
  {
    'name': 'the future of mathematics',
    'author': 'david wilson',
    'publisher': 'penguin books',
    'classification': 'engineering',
    'year': '1655',
    'volumes': 2,
    'pages': 611,
  },
  {
    'name': 'modern technology',
    'author': 'mary thomas',
    'publisher': 'penguin books',
    'classification': 'religion',
    'year': '1688',
    'volumes': 3,
    'pages': 858,
  },
  {
    'name': 'foundations of engineering',
    'author': 'mary thomas',
    'publisher': 'simon & schuster',
    'classification': 'medicine',
    'year': '1650',
    'volumes': 3,
    'pages': 977,
  },
  {
    'name': 'modern psychology',
    'author': 'linda martinez',
    'publisher': 'bantam books',
    'classification': 'art',
    'year': '1719',
    'volumes': 2,
    'pages': 715,
  },
  {
    'name': 'understanding astronomy',
    'author': 'sarah lee',
    'publisher': 'scholastic',
    'classification': 'history',
    'year': '1855',
    'volumes': 1,
    'pages': 540,
  },
  {
    'name': 'introduction to literature',
    'author': 'robert anderson',
    'publisher': 'springer',
    'classification': 'psychology',
    'year': '1938',
    'volumes': 3,
    'pages': 947,
  },
];